// Auth
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

// Users
export const INDEX_USER = 'INDEX_USER';
export const INDEX_USER_SUCCESS = 'INDEX_USER_SUCCESS';
export const INDEX_USER_ERROR = 'INDEX_USER_ERROR';

export const STORE_USER = 'STORE_USER';
export const STORE_USER_SUCCESS = 'STORE_USER_SUCCESS';
export const STORE_USER_ERROR = 'STORE_USER_ERROR';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const SHOW_USER = 'SHOW_USER';
export const SHOW_USER_SUCCESS = 'SHOW_USER_SUCCESS';
export const SHOW_USER_ERROR = 'SHOW_USER_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const DESTROY_USER = 'DESTROY_USER';
export const DESTROY_USER_SUCCESS = 'DESTROY_USER_SUCCESS';
export const DESTROY_USER_ERROR = 'DESTROY_USER_ERROR';

// Teams
export const INDEX_TEAM = 'INDEX_TEAM';
export const INDEX_TEAM_SUCCESS = 'INDEX_TEAM_SUCCESS';
export const INDEX_TEAM_ERROR = 'INDEX_TEAM_ERROR';

export const STORE_TEAM = 'STORE_TEAM';
export const STORE_TEAM_SUCCESS = 'STORE_TEAM_SUCCESS';
export const STORE_TEAM_ERROR = 'STORE_TEAM_ERROR';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR';

export const SHOW_TEAM = 'SHOW_TEAM';
export const SHOW_TEAM_SUCCESS = 'SHOW_TEAM_SUCCESS';
export const SHOW_TEAM_ERROR = 'SHOW_TEAM_ERROR';

export const UPDATE_TEAM = 'UPDATE_TEAM';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_ERROR = 'UPDATE_TEAM_ERROR';

export const EDIT_TEAM = 'EDIT_TEAM';
export const EDIT_TEAM_SUCCESS = 'EDIT_TEAM_SUCCESS';
export const EDIT_TEAM_ERROR = 'EDIT_TEAM_ERROR';

export const DESTROY_TEAM = 'DESTROY_TEAM';
export const DESTROY_TEAM_SUCCESS = 'DESTROY_TEAM_SUCCESS';
export const DESTROY_TEAM_ERROR = 'DESTROY_TEAM_ERROR';


// Competitions
export const INDEX_COMPETITION = 'INDEX_COMPETITION';
export const INDEX_COMPETITION_SUCCESS = 'INDEX_COMPETITION_SUCCESS';
export const INDEX_COMPETITION_ERROR = 'INDEX_COMPETITION_ERROR';

export const STORE_COMPETITION = 'STORE_COMPETITION';
export const STORE_COMPETITION_SUCCESS = 'STORE_COMPETITION_SUCCESS';
export const STORE_COMPETITION_ERROR = 'STORE_COMPETITION_ERROR';

export const CREATE_COMPETITION = 'CREATE_COMPETITION';
export const CREATE_COMPETITION_SUCCESS = 'CREATE_COMPETITION_SUCCESS';
export const CREATE_COMPETITION_ERROR = 'CREATE_COMPETITION_ERROR';

export const SHOW_COMPETITION = 'SHOW_COMPETITION';
export const SHOW_COMPETITION_SUCCESS = 'SHOW_COMPETITION_SUCCESS';
export const SHOW_COMPETITION_ERROR = 'SHOW_COMPETITION_ERROR';

export const UPDATE_COMPETITION = 'UPDATE_COMPETITION';
export const UPDATE_COMPETITION_SUCCESS = 'UPDATE_COMPETITION_SUCCESS';
export const UPDATE_COMPETITION_ERROR = 'UPDATE_COMPETITION_ERROR';

export const EDIT_COMPETITION = 'EDIT_COMPETITION';
export const EDIT_COMPETITION_SUCCESS = 'EDIT_COMPETITION_SUCCESS';
export const EDIT_COMPETITION_ERROR = 'EDIT_COMPETITION_ERROR';

export const DESTROY_COMPETITION = 'DESTROY_COMPETITION';
export const DESTROY_COMPETITION_SUCCESS = 'DESTROY_COMPETITION_SUCCESS';
export const DESTROY_COMPETITION_ERROR = 'DESTROY_COMPETITION_ERROR';
